### ISSUE TITLE
Admin should be able to approve a pending transaction from that user's page

### ISSUE THREAD

**Issue by alexbckr** [alexbckr/vrpay#11]
As an admin, I want the option to approve a transaction directly from a user's page so that I don't have to navigate to the admin page.

"Edit/Approve" should appear on pending transactions alongside the option to edit when the user is an admin.
<img width="291" alt="Screen Shot 2022-07-20 at 10 33 33 PM" src="https://user-images.githubusercontent.com/58566949/180137150-f40964ce-d1fc-4eaa-be6a-1d69fb588c95.png">

When clicking this option, the user should see an overlay with autofilled fields (based on the pending transaction).
<img width="485" alt="Screen Shot 2022-07-20 at 10 39 10 PM" src="https://user-images.githubusercontent.com/58566949/180137795-d8ba8fcd-885a-434c-af3a-7f10f283ec16.png">

The user now has the option to approve the transaction or to cancel. If the admin cancels, there is no impact on the transaction. If the user approves the transaction, the pending transaction is updated with the information from the Admin's approval (if it has been edited) and it becomes an approved transaction. The transaction should impact the user's total due.

**Comment by nfl6fh** [comment]
I'll take this
