### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by alexbckr** [alexbckr/vrpay#2]
We should have an admin page (dashboard) where admins can view (1) user lists, (2) pending transactions to approve, and (3) create transactions. For this issue, just focus on creating the page.
<img width="833" alt="Screen Shot 2022-07-19 at 12 06 18 AM" src="https://user-images.githubusercontent.com/58566949/179687753-af1281e4-c035-4966-963d-8296f7d187a5.png">

The page should appear at `/dashboard`. Users marked as admins should be able to visit the admin page through a button in the custom navbar.
<img width="738" alt="Screen Shot 2022-07-19 at 12 08 46 AM" src="https://user-images.githubusercontent.com/58566949/179688254-6a87b02d-5c20-4886-8fc2-69b4971ce226.png">

This button should be visible on all pages that have the custom navbar, but it should NOT be visible if the current user is not an admin. Check out the code for VRA Connect's admin page. (there's some similar logic for when to display the button/admin page stuff)

When an admin logs in, they should be redirected to the dashboard (/dashboard) and not their user page (which is how it currently works for all users that are not admins).

**Comment by nfl6fh** [comment]
comment
