### ISSUE TITLE
Admin page should display (1) a list of users that are not verified and (2) a list of users that have been verified

### ISSUE THREAD

**Issue by alexbckr** [alexbckr/vrpay#4]
Hard-coding things in the DB is unsustainable (believe me). It's much easier to be able to open the site and approve/deny people through a dashboard, and future admins won't know how to do the prisma thing. We should allow the admin to view verified and unverified users through the dashboard (this is the first step to making a bunch of cool stuff here).
<img width="518" alt="Screen Shot 2022-07-19 at 12 20 55 AM" src="https://user-images.githubusercontent.com/58566949/179690689-1b537b56-ede0-4ac4-bad5-a9218aab88a2.png">

When there are users that are not verified, a table should appear where the admin can accept or deny (delete) those users (that functionality is outside the scope of this issue). If there are no unverified users, this table should be completely invisible.

There should also be a list of all verified users, displaying their name, email, and amount due. Their name should link to their user page (/id) for easy access.

Tips:
- look at VRA connect's admin page for the calls to the DB here. You essentially find all users where verified is false, and find all users where verified is true.

**Comment by kmrowed** [comment]
okay! I will take this!
