### ISSUE TITLE
Admin should be able to approve a transaction from the admin dashboard

### ISSUE THREAD

**Issue by alexbckr** [alexbckr/vrpay#7]
As an admin, I want to be able to view all pending transactions without having to navigate to each user's individual page.

A list of pending transactions should appear in the admin dashboard (much like the lists of users) and it should have all information relevant to the transaction visible. An admin should have the option to approve a transaction directly from that list.

Once approved, the transaction should impact the relevant user's total due.

**Comment by kmrowed** [comment]
I'd love to try and tackle this.
